### ISSUE TITLE
Windows Native Build?

### ISSUE THREAD

**Issue by lonnietc** [rqlite/rqlite#1004]
Hello,

I am researching highly distributed database systems and am interested in databases that can be cross-compiled for a number of different platforms.

In researching Rqlite, it seems that I get errors with trying to do a native build with G0 v1.16 and the github site says that a Windows build needs to use AppVeyor.

Is this likely to change in the future so that Go will build it nicely on Windows as well?

My my interests are toward possibly using Rqlite in a P2P system that could produce clusters of many thousands of nodes at any give time.

One idea was to also possibly use Rqlite as a replacement backend in the Cayley Graph Database layer in which they currently have support for Sqlite to see if it might be possible to have Cayley working in a nice distributed fashion by letting the Rqlite nodes manage the data in a distributed way.

Suggestions or ideas would be greatly appreciated and I am still trying to determine if Rqlite is right for the job?

**Comment by otoolep** [comment]
Why can't you build for Windows? Appveyor is simply a CI system that builds Go binaries on Windows. Have you actually tried to build it on Windows?

It's simple build process:
https://github.com/rqlite/rqlite/blob/master/CONTRIBUTING.md#building-rqlite
https://github.com/rqlite/rqlite/blob/master/appveyor.yml#L20

>My my interests are toward possibly using Rqlite in a P2P system that could produce clusters of many thousands of nodes at any give time.

rqlite is not a good fit for this use case, due to the nature of the Raft protocol.

https://github.com/rqlite/rqlite/blob/master/DOC/FAQ.md#is-rqlite-a-good-match-for-a-network-of-nodes-that-come-and-go----perhaps-thousands-of-them

**Comment by lonnietc** [comment]
Thanks for the information on this and I will continue my research on ideas that I have for this project.
