### ISSUE TITLE
No ARM-images on Docker-Hub

### ISSUE THREAD

**Issue by a-bran** [rqlite/rqlite#1077]
Hello,
i'd like to request adding ARMv7/8-images on Docker-Hub or another repository of choice.

Based on [this blog-post](https://www.philipotoole.com/rqlite-7-6-0-released/) i thought its already available, but sadly only the binary-releases include ARM-builds.

**Comment by NerdyShawn** [comment]
Hello everyone!
I am excited for this feature as well and I was able to build a [multi-platform image](https://docs.docker.com/build/building/multi-platform/) locally to run on a raspberry pi here. So what I believe this issue is related to the CI portion that builds the image to docker with only **x64** currently. Correct me if I'm wrong but i think it might be with circleci having to define "**docker buildx ** support for the multi-architecture image to pull. So I attempted a pull request to the rqlite-docker repo that did not work. 

Sorry I'm not as familiar with the circleci config but I signed up for my own personal account attempting to replicate what I had achieved locally on my laptop with buildx that whatever the image pipeline could support that relatively newer feature for multi cpu architecture builds. Its neat it even uses [qemu](https://www.qemu.org/) to build the other desired architectures. I haven't been able to figure it out yet from the support documentation based on my current understanding of what could work if it supports a new docker version with buildx defined.

Shameless plug as I would like to help more if I can so I joined the slack workspace as well. I'm sure there are other options as well that I'm curious to help figure out how we can all benefit from the public hosted image supporting multi-platform. Its really nice running it in kubernetes clusters of mixed cpu architecture for example without having to modify the image manifests. Thanks for reading the issue as I understand it and I hope this helps us.

**Reference:**

- This was my pull request attempt that we had to revert https://github.com/rqlite/rqlite-docker/pull/13
- [How to use Docker Buildx in Remote Docker](https://support.circleci.com/hc/en-us/articles/360058095471-How-To-Use-Docker-Buildx-in-Remote-Docker-)

**Comment by soonoo** [comment]
For those who want to build and run rqlite in ARM, I put a tweaked Dockerfile and docker-entrypoint.sh on the gist.  

It seems that alpine image has musl-related issue with arm64 build of rqlite. So I changed the base image to ubuntu, and the size of the final image got bigger. (30mb -> 140mb)
Also I'm not sure if this can be used for production environment.

Download both files from below link and run `docker build .`
https://gist.github.com/soonoo/710d0f60a0d4643c68cc12a16d20abdf

**Comment by otoolep** [comment]
https://github.com/rqlite/rqlite/pull/1591

**Comment by otoolep** [comment]
Fixed by https://github.com/rqlite/rqlite/commit/070d6c09748cdc445cdbbb4ddd09406eff2002b6
