### ISSUE TITLE
Empty types are returned for aggregate expression columns

### ISSUE THREAD

**Issue by dan-blum** [rqlite/rqlite#1330]
I am running rqlite 7.5.0, but I don't see any related closed issues so I assume this is reproducible on the current version.

To reproduce, run the command-line client and issue these statements:

create table foo(id integer not null primary key, name text, amt real);
insert into foo(name, amt) values("a", 123.45);
insert into foo(name, amt) values("b", 10.01);

Then 

curl -G 'localhost:0/db/query?pretty' --data-urlencode 'q=SELECT sum(amt) FROM foo'

Results:
{
    "results": [
        {
            "columns": [
                "sum(amt)"
            ],
            "types": [
                ""
            ],
            "values": [
                [
                    133.46
                ]
            ]
        }
    ]

I'm not sure what information sqlite is providing here so I am not sure where the ball is being dropped.

**Comment by otoolep** [comment]
Thanks for the report, you are correct it's been like this for a while, and is due to a shortcoming in the underlying Go SQL driver.

https://pkg.go.dev/database/sql#ColumnType.DatabaseTypeName

"If an empty string is returned, then the driver type name is not supported."

Let me look into this some more, perhaps it's something easy to fix in https://github.com/mattn/go-sqlite3 (or I am using the driver incorrectly).

**Comment by otoolep** [comment]
OK, as I suspected, this is due to the way SQLite works. If you trace through the code for rqlite, you will eventually end up here in the underlying Go driver:

https://github.com/mattn/go-sqlite3/blob/v1.14.17/sqlite3.go#L2134C50-L2134C73

This calls the SQLite function https://www.sqlite.org/c3ref/column_decltype.html, which states:

>If the Nth column of the result set is an expression or subquery, then a NULL pointer is returned.

This function will return `NULL` because `sum()` is an expression. So this explains what we're seeing right now. However it's actually pretty easy to fix this -- and I should have spotted it earlier.  Patch coming.

**Comment by otoolep** [comment]
Thanks again for the report, I will release 7.21.3 shortly, which will contain the fix for this issue.

**Comment by otoolep** [comment]
https://github.com/rqlite/rqlite/releases/tag/v7.21.3
