### ISSUE TITLE
Impact of Hashicorp relicense to BUSL?

### ISSUE THREAD

**Issue by moderation** [rqlite/rqlite#1363]
Hashicorp re-licensed their core products to the Business Source License (BUSL 1.1) which means their products are no longer open source.

- [Announcement](https://www.hashicorp.com/blog/hashicorp-adopts-business-source-license)
- [FAQ covering what products are impacted](https://www.hashicorp.com/license-faq#What-products-will-be-covered-by-BSL-1.1-in-their-next-release) 

`rqlite` uses several libraries from Hashicorp - https://github.com/search?q=repo%3Arqlite%2Frqlite+hashicorp&type=code

Will there be any impact on `rqlite`? In theory `rqlite` isn't a competitive commercial product but clarification would be nice.

**Comment by otoolep** [comment]
[IANAL](https://en.wikipedia.org/wiki/IANAL).

Since Hashicorp's licensing changes [are not retroactive](https://www.hashicorp.com/license-faq#Can-I-continue-to-use-versions-of-the-products-that-were-provided-under-the-original-MPL-2.0-license), rqlite is not currently affected.

And unless Hashicorp a) updates source code that rqlite actually uses, b) changes the license of that source to BUSL, **and** c) rqlite then starts using those new versions, rqlite will not be affected. Even when all of those things are true, rqlite may still not be affected.
