### ISSUE TITLE
Binding parameters in queries?

### ISSUE THREAD

**Issue by rse** [rqlite/rqlite#140]
Perhaps I'm overlooking it, but it seems that RQLite requires all values to be sent in SQL-escaped form over the wire. Wouldn't it be better if one could send e.g. JSON over the wire (e.g. '{ query: "INSERT INTO foo VALUES (?, ?);", params: [ "foo", "bar" ] }') because in mostly all client environments JSON can be easily generated in a robust way (including the escaping of values for JSON). In other words: IMHO being able to separate binding parameters from the actual query and encoding both in a particular language like JSON could simplify clients and allow clients to reuse their perhaps complex queries, too.

**Comment by otoolep** [comment]
Thanks @rse 

I follow what you're suggesting, but I don't particularly think it would be much better. I wanted to rqlite to provide the thinnest possible layer between the user and the SQLite database, so the queries one sends to rqlite are exactly the same one would send to a SQLite database. There is nothing arbitrary about it.

What you suggest, which would work, would still require the client to transform their requests into the JSON rqlite would expect, and it's somewhat arbitrary. Does the API use `params`, `values`, etc.  So rqlite leaves it entirely up to clients to generate the SQL commands, and pass them in fully-formed.

I would certainly merge a patch that added something like the functionality you suggest (basically prepared statements), but it would be a different endpoint. I always want to support the current functionality.

**Comment by otoolep** [comment]
I'm definitely interested in looking into this functionality, but would like more examples of use cases and how this helps users write less code.

**Comment by keisisqrl** [comment]
It could help with code complexity by allowing frequently-used queries to have values swapped out on the fly instead of reconstructing the query string. Though prepared queries as seen in #152 may do that even more. 

The main advantage from my point of view for parameterized queries is that they're the safest way to avoid SQL Injection when dealing with arbitrary user data. 

Based on the db code here and the upstream library I think I can see how to do implement this. I may have a whack at it.

**Comment by raindog308** [comment]
In traditional RDBMS systems, bind values are an important key to performance.  Without them, the engine has to hard parse the query every time (figure out the optimizer plan, etc.), as opposed to just substituting variables against a plan it's already computed.

I don't know if SQLite caches previous query plans, etc.  If it does, then avoiding hard parses improves performance.  If it doesn't, then every operation is a hard parse.

An important additional benefit is it gets the developer out of all the hideous quoting, and it helps avoids the class of problems around misquoting like SQL injection, as keisisqrl mentioned.

The real answer here is a proper golang database/sql driver for rqlite.  Is that in the cards?  I'm new :-)

**Comment by keisisqrl** [comment]
[go-sqlite3's Exec](https://github.com/mattn/go-sqlite3/blob/master/sqlite3.go#L529) supports one-shot parameterized queries. [rqlite's Execute function](https://github.com/rqlite/rqlite/blob/master/db/db.go#L126) currently does not and uses subsequent arguments as additional queries to execute, so this would require modifications to the internal API as well as a new JSON endpoint. The same is true of Query in [go-sqlite3](https://github.com/mattn/go-sqlite3/blob/master/sqlite3.go#L562) vs [rqlite](https://github.com/rqlite/rqlite/blob/master/db/db.go#L219).

**Comment by zweifisch** [comment]
I am using https://github.com/mysqljs/sqlstring for escaping, but mysql is a bit different from sqlite, is there something similar like this package, but for sqlite?

**Comment by zmedico** [comment]
> I am using https://github.com/mysqljs/sqlstring for escaping, but mysql is a bit different from sqlite, is there something similar like this package, but for sqlite?

From https://www.sqlite.org/lang_expr.html:

    A string constant is formed by enclosing the string in
    single quotes ('). A single quote within the string can
    be encoded by putting two single quotes in a row - as in
    Pascal. C-style escapes using the backslash character are
    not supported because they are not standard SQL.

    BLOB literals are string literals containing hexadecimal
    data and preceded by a single "x" or "X" character.
    Example: X'53514C697465'

**Comment by tracker1** [comment]
One problem I've seen, is at least with mysql, that some characters (depending on encoding) are "equivalent" to `'` in terms of SQL escapes, for example the pretty single-quote that might copy/paste in/out of Word or another word processor.  Another issue, is how does your service deal with UTF8 character codes?  Is all SQLite data in the database UTF-8?

This was literally the first thing I expected was for queries to be something like...

    ["INSERT INTO Foo (ColumnA, ColumnB) VALUES (?, ?)","value1","value2"]

Or with named parameters.

    ["INSERT INTO Foo (ColumnA, ColumnB) VALUES (@v1, @v2)",{"v1":"value1","v2":"value2"}]

The everything is a string interface is just begging to see some sort of SQL injection attack imho.  And at least with other databases if it isn't part of the interface is inviting chaos down the road.

**Comment by nicktimko** [comment]
To try to motivate this some more, injection is the number 1 ([on the OWASP top 10](https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A1-Injection)) security bug in tons of systems and there are [blog posts](https://blog.codinghorror.com/give-me-parameterized-sql-or-give-me-death/) and [comics](https://xkcd.com/327/) about it. Parameterized queries/binding parameters is, in my mind, all about the security. Possible performance improvements are just a nice side effect.

SQLite, like other databases, provides [parameter binding methods](https://www.sqlite.org/lang_expr.html#varparam), so a "raw" interface that RQLite wants to provide could still have such things. An endpoint that provides something like `db.Exec`: a string query argument, then 0 or more `arg` args for parameters seems like it could fit into the HTTP API.

Broadly, I guess the three possible places to do query binding

1. Force the client to do the binding themselves (easiest, i.e. no work/status quo). This requires that all clients written in all languages correctly implement escaping (maximum possibility for bugs)
1. Bind the parameters to the query when received by RQLite in the HTTP handler. This narrows the problem considerably by just ensuring that there is *one* implementation of this to worry about, and is probably much easier than...
1. Pass parameters into the Raft log for what to be applied to the node's state. I can't quite trace C/Go interfaces yet, but mattn/go-sqlite3 seems to be using the SQLite C API to prepare the query and [bind parameters](https://github.com/mattn/go-sqlite3/blob/53cff3fcebd1e177d04129dc131523635bc45d3d/sqlite3.go#L1788-L1843). This then places the responsibility of binding at SQLite's feet, and because it compiles ("prepares") the query *before* binding occurs, whatever malicious text is in the parameter can't alter query execution.

Maybe we could extend the HTTP API so requests look like the below. The use of parameters could maybe be autodetected (is the object in the array another array or just a string), or could just force the client to provide a query param which would insist all queries in the list are in `[query, args ...]` format.

```diff
 [
-    "SELECT * FROM foo WHERE name = \"bob\""
+   ["SELECT * FROM foo WHERE name = ?", "bob"]
 ]
```

Supporting named parameters is a "would be nice" feature IMHO.

As a PS, I dug into this hole when I found that passing question marks (`?`) in what look like query parameters to pyrqlite cause a bug to occur. That the Python code is doing the query binding is slightly worrying.

**Comment by otoolep** [comment]
Thank you @nicktimko, fo your detailed suggestions. I will spend sometime thinking about this issue, and how it could be best implemented. At first glance your API suggestion makes sense.

**Comment by otoolep** [comment]
I'm implementing this feature in https://github.com/rqlite/rqlite/issues/140, as per the API suggestion by @nicktimko

**Comment by otoolep** [comment]
Thanks again to @nicktimko for the API suggestion.

**Comment by otoolep** [comment]
Opened new issue to follow up on named parameters.

https://github.com/rqlite/rqlite/issues/675
