### ISSUE TITLE
CLI should accept list of nodes

### ISSUE THREAD

**Issue by otoolep** [rqlite/rqlite#157]
This would allow the CLI to try connecting to a different node is the first node goes down.

**Comment by mainframe** [comment]
+1

**Comment by otoolep** [comment]
A better approach would be to have the Go client library (which needs to be fully developed) implement this functionality. It should not be CLI-specific. Then the CLI would use the new client library.

**Comment by snapo** [comment]
maybe dns in a records? or a hostlist json file? ... just some ideas :-)

**Comment by otoolep** [comment]
Adding it the CLI is definitely an option though.

**Comment by chermehdi** [comment]
Is somebody working on this? Seems like something that I can take on if nobody is actually doing it

**Comment by otoolep** [comment]
Still needs to be done -- contributions welcome. Please read https://github.com/rqlite/rqlite/blob/master/CONTRIBUTING.md

**Comment by chermehdi** [comment]
A couple of clarifications:

* By the CLI do we mean the `rqlite` or the `rqlited`? i.e do we need to specify the list of nodes to try to connect to as a client (rqlite), or specify the list of existing cluster nodes (rqlited)?

**Comment by otoolep** [comment]
We mean the CLI, the code here: https://github.com/rqlite/rqlite/tree/master/cmd/rqlite

Before you do any significant coding, I suggest you show us what you plan to do in terms of a) the experience of using the CLI with this functionality in place, and what exactly it will do with those extra options. For instance, how will failure be detected, any retry, what node will be tried next, and when would the CLI give up (if at all).

**Comment by chermehdi** [comment]
What I had in mind for this was:

Introduce a new struct to wrap the HTTP client calls which will be aware of extra things:

* Nodes that we wish to send queries to
* Health status of this node (checked and updated in the background)
* (optionally) A retry policy + a maximum timeout to respond before considering the node as unavailable).

- Instead of calling `http.Client.Do` directly we would call a proxy method on the client which will forward to one of the available hosts.

- If we are unable to connect to a node, we prompt to the user that the host is unavailable and we are trying another host, if that host is successful following requests will be sent to that host, a host change is only required if the active host is unavailable.
- A goroutine will continuously check host availabilities (every `X seconds`) on some `/healthz` API available on the node (not sure if that already provided by the nodes) and update the list of hosts that are unavailable.

**Comment by otoolep** [comment]
This sounds reasonable except for one point -- the background checking. It's unnecessary. Just implement your logic for a downed node when you attempt to interact with that node. If a given node fails to respond, then go to the next node (or whatever your logic will be). That logic will execute in milliseconds, faster that any end user will notice. The end user's experience will be identical.

**Comment by otoolep** [comment]
>when you attempt to interact with that node
As a result of the end user issuing a command at the prompt, of course.

**Comment by otoolep** [comment]
Also, in terms of implementation, I suggest you break the node-choosing logic into a distinct module that the can be unit tested well. You can fake the nodes via very simple HTTP test servers, have them appear to come and go.

https://pkg.go.dev/net/http/httptest

**Comment by chermehdi** [comment]
After thinking about it a bit more, you are right, background health checks seems like an overkill.

What do you recommned for checking healthiness? Ability to connect or a `/healthz` endpoint response?

**Comment by otoolep** [comment]
>What do you recommned for checking healthiness? Ability to connect or a /healthz endpoint response?

Nothing so complicated. Just make the HTTP request as normal (to the query endpoint, execute endpoint, whatever) and a) handle the timeout error that will come back if the node is down, or b) the possibly HTTP 503 a node can return if it needs a leader, but can't find one. Make sense?

Perhaps the initial comment in this issue should be clearer, which might help. This issue could be defined as:

"CLI should accept a list nodes, such that if a query or execute HTTP request to the node fails, then the CLI can try another node in the list. _Fails_ is defined as _node does not respond at all to the HTTP request at all, or the node returns anything but HTTP 200, 301, or 302 (503, 500, 404 for example)_."

**Comment by otoolep** [comment]
Fixed -- thanks for your help, @chermehdi
