### ISSUE TITLE
Add the ability to read credentials via secure environment variables

### ISSUE THREAD

**Issue by jasonwillschiu** [rqlite/rqlite#1846]
**Is your feature request related to a problem? Please describe.**
I'm trying to add basic auth credentials securely inside of fly.io using docker. At the moment I have it working via copying the config.json credentials into my docker image and then passing it with -auth config.json. It doesn't seem secure enough and I'm not a security or docker expert, but I think it'd be nice to pass credentials to -auth via stringified json.

I've seen that you can pass files to docker run via a volume, but that doesn't seem secure either.

Happy for your suggestions, maybe I'm missing something.

**Describe the solution you'd like**
Reading from secure environment variables like fly secrets. Maybe in stringified json format
`rqlited -auth '[{"username":"bob","password":"secret1","perms":["all"]}]'`
and it'll look like
`rqlited -auth MY_SECRET`

**Comment by otoolep** [comment]
cc @jtackaberry who may have some ideas.

@jasonwillschiu - it would probably be straightforward enough to have `-auth` accept a file (as it does today) or an actual JSON string. In fact I follow that pattern in other places. So what you suggest should be easy enough. But If someone dumps a process table, and sees command line args, wouldn't your secrets be exposed?

Alternatively would environment variables be a more secure approach? The idea being we modify https://github.com/rqlite/rqlite/blob/master/docker-entrypoint.sh so that it looks out for a environment variable, which contains the auth info in JSON form? Are you building your own Docker images?

**Comment by jasonwillschiu** [comment]
In my case (using flyio secrets) I don't think that a ps dump would show anything because the environment variable would already be there `rqlited -auth MY_SECRET`, but you're right about in general that being an issue if someone uses a text json string in the cli.

Modifying the docker-entrypoint.sh to look for an environment variable would work too.

I'm basically running the stock image. I also haven't tried clustering yet, so if my advertised addresses look wrong, they probably are haha.

```
# Use the official rqlite image
FROM rqlite/rqlite:latest

# Copy the credentials file
COPY creds.json creds.json

# Expose the ports
EXPOSE 4001 4002

# Run the rqlited command
CMD ["rqlited", "-http-addr", "0.0.0.0:4001", "-http-adv-addr", "localhost:4001", "-raft-addr", "0.0.0.0:4002", "-raft-adv-addr", "localhost:4002", "-auth", "creds.json", "db"]

```

**Comment by otoolep** [comment]
OK, that's definitely a bit awarded. Are you sure Fly doesn't offer some sort of way of mounting a file system, such that it is available at path X from `rqlited` running inside the container? If it does, then you pass that path when lauching the container. E.g.

docker run rqlite/rqlite -auth X

**Comment by jtackaberry** [comment]
Configuration through environment variables is certainly a common practice with containerized services.  I wouldn't want config to be *exclusively* provided by env vars (and so I disagree with [this 12-factor app principle](https://12factor.net/config)), but it's not uncommon to support both config files and env vars such that any configuration can be provided by either -- or even both (where env vars typically override).

Using environment variables for *secrets* is [generally discouraged](https://aws.github.io/aws-eks-best-practices/security/docs/data/#use-volume-mounts-instead-of-environment-variables), with the usual reason being that some software will log the environment as part of debugging, which means secrets will get leaked in container logs.  This isn't a strong argument when the software being run is fully known (as in rqlite's case).

Still, in the day job, I generally discourage the practice of exposing secrets as env vars Just In Case, and also because when it's stored in a file, runtime protection tools (such as Falco) can provide an audit trail of when files containing secrets was read and by which pid.  And, being stored in a file, it at least opens the door for dynamic reloading (even though most software [rarely](https://github.com/rqlite/rqlite/issues/1553) actually [supports that](https://github.com/rqlite/rqlite/issues/1554) :)).

But that's all well and good for Kubernetes, which has pretty good native support for this (via ConfigMaps and Secrets).  In other container environments, it's not so easy.  Amazon's own Elastic Container Service for example is nightmarish here, and the simplest and best supported pattern encourages putting secrets in env vars.  Maybe Fly.io is similar (I'm not familiar with it).

So I wouldn't necessarily argue against this, but I wonder if a more general approach would be preferred, such that any configuration can be specified by environment variables?

For example, in my Go projects I use [spf13/viper](https://github.com/spf13/viper) which supports config coming from config files, env vars, and command line arguments (when paired with [spf13/cobra](https://github.com/spf13/cobra)).

**Comment by jasonwillschiu** [comment]
Thanks for sense checking me and explaining why env vars aren't generally used for secrets, very helpful! 

I got it working by mounting in the [[files]] section of the config, different to the [[mounts]] section in Fly. In case anyone is stuck with fly.io deployment

```
app = 'rqlite5'
primary_region = 'syd'

# mount file at runtime
[[files]]
guest_path = "/secrets/creds.json"
local_path = "/absolute/local/path/creds.json"

[experimental]
cmd = [
  '-http-allow-origin=https://libsqlstudio.com',
  '-auth',
  '/secrets/creds.json',
]

[build]
# don't need my dockerfile anymore
# dockerfile = 'Dockerfile'
image = "rqlite/rqlite:latest"

[env]
HTTP_ADDR = '0.0.0.0:4001'
NODE_ID = '1'
RAFT_ADDR = '0.0.0.0:4002'

[[mounts]]
source = 'db'
destination = '/rqlite/file/data'


[[services]]
protocol = 'tcp'
internal_port = 4001
force_https = true
# keep machines continuously on
auto_stop_machines = "off"
auto_start_machines = false

[[services.ports]]
port = 4001
handlers = ['tls']

[[services]]
protocol = 'tcp'
internal_port = 4002
force_https = true
auto_stop_machines = "off"
auto_start_machines = false

[[services.ports]]
port = 4002
handlers = ['tls']

# only for testing to stop it restarting 10x
# [[restart]]
# policy = 'never'

[[vm]]
size = 'shared-cpu-1x'
```
