### ISSUE TITLE
Possible to force new master election?

### ISSUE THREAD

**Issue by raindog308** [rqlite/rqlite#192]
I have a cluster, and all work will go through one node forever until something breaks.  That's not a huge problem, but it'd be nice to move the load around, if for no other reason than to periodically test the cluster and make sure all nodes are truly ready to become the master.

I can force an election by restarting rqlite on the current master (which of course forces the other nodes to pick a new leader while the previous master comes back up) but it would be nice if there was an API call.

Unfortunately, I didn't see anything in the underlying raft library that exposed this.

**Comment by otoolep** [comment]
"Spreading load around the cluster" doesn't make a huge amount of sense to me. Since rqlite is a leader-type system, all traffic has to go through the leader. If a node does not have the resources (CPU, disk, RAM, etc) necessary to serve as a leader, it shouldn't be in the cluster. rqlite does not, as I am sure you understand, distribute for scale. It distributes for reliability.

As for an endpoint to force an election, I could think of ways to do it, but it would pollute the implementation of rqlite. As you've been doing, forcing these kind of failures yourself is the best approach.

I'll leave this ticket open in case I am missing a good use case, but I don't see myself doing anything here.

**Comment by otoolep** [comment]
Closing as I don't see this getting done.
