### ISSUE TITLE
Add native binaries and package distribution

### ISSUE THREAD

**Issue by fern4lvarez** [rqlite/rqlite#23]
As of now, you need Go installed to install rqlite. Given the nature of this project, this might be inadequate in many cases, as you just want to start a sqlite cluster without further dependencies.

Go comes to the rescue here, as it makes it super easy to cross compile the program and generate binaries for different OSs and architectures. Tools like [`gox`](https://github.com/mitchellh/gox) make it even easier to automate.

First question we need to answer is, is there currently any restriction to run rqlite on any of the most popular platforms (linux, darwin, windows)? Is there something to improve first on this matter (i.e. specific build tags)?

**Comment by otoolep** [comment]
No, I don't *think* there should be any problems, though this project does use some C code, so I can't be sure. I haven't tested cross-compilation.

Where would you store the debian and RPM packages? Are you thinking about a repo service?

**Comment by fern4lvarez** [comment]
https://packagecloud.io/ provides a very nice service. Projects like [inspeqtor](https://github.com/mperham/inspeqtor/wiki/Installation) are using it.

**Comment by otoolep** [comment]
Ah yes, I am  familiar with that service. It would be cool to get packages up there.

**Comment by tchoulihan** [comment]
For my case, where I'm mainly interfacing with rqlite through curl, I make sure I have go installed, then run shell scripts to setup/rejoin rqlite. My program is written in java, but any language could pretty easily interface with rqlite since it uses curl. 

IMO, its not too much to ask that users have go installed to be able to run go programs.

**Comment by otoolep** [comment]
Well, that's the thing @tchoulihan -- unlike Java, one doesn't need Go to run Go programs. Since they are compiled as binaries without any external dependencies (not counting libc), it is of great value to have the binaries packaged as standalone programs. This is in contrast to Java, where even if you package up all the source and JAR files, one *still* needs the JVM installed. (Apologies if you know all this!)

**Comment by tchoulihan** [comment]
Understood, its cool that its a possibility. I have to have ruby, python, java, and libc installed on my machine haha.

**Comment by mainframe** [comment]
+1 for rpm (centos 7) and deb (ubuntu 16.04) native packages.

**Comment by StarpTech** [comment]
+1 for windows support

**Comment by thefonzi** [comment]
+1 one windows packages

**Comment by otoolep** [comment]
Windows binaries are built during CI, this is all I'm going to do here for now.
