### ISSUE TITLE
deleting nodes not working

### ISSUE THREAD

**Issue by varunudacity** [rqlite/rqlite#351]
curl -L -XDELETE http://discovery.rqlite.com/2ffee44c-94e1-11e7-a0f4-bed94f538e59 -H "Content-Type: application/json" -d '{"addr": "localhost:4001"}'
{"error": "bad request body"}

Also, I recommend adding the "-L" flag to the .md file, so that curl follows redirects

**Comment by otoolep** [comment]
Thanks for the report @varunudacity -- you are right, this is not working. Even passing `-L` to the command won't fix this, since the node to delete is listed in the body of the command, and the body is not included when `curl` redirects the request. Without a proper body, the Discovery service responds with 400.

I need to think about this. In the meantime, if you need to delete a node you can go straight to the AWS Lambda gateway as follows:

```
curl -XDELETE -v 'https://k05nh959gb.execute-api.us-west-2.amazonaws.com \
/prod/rqliteDiscoHandler/<disco_id>' -H "Content-Type: application/json" \
-d '{"addr": "localhost:4001"}
```

**Comment by varunudacity** [comment]
Thanks. A related question: if I reconfigure the raft cluster, via the
client, will that automatically update the discovery service?

Maybe returning status code 307 would work?

https://softwareengineering.stackexchange.com/questions/99894/why-doesnt-http-have-post-redirect

**Comment by otoolep** [comment]
>if I reconfigure the raft cluster, via the client, will that automatically update the discovery service?

I don't really follow what you have in mind. Can you provide me with a concrete example?

**Comment by varunudacity** [comment]
Perhaps rqlite doesn't support this yet, but raft has additional commands
for adding and removing peers from the cluster. These membership changes
are done in a particular way to ensure that two nodes do not become leaders
at the same time.

Concrete use case:
I have three nano servers on ec2. My rqlite memory usage is going up and I
want to upgrade. I would like to add 3 bigger instances (e.g m4.medium) and
remove the original servers entirely. What should happen with raft is that
the new servers will be brought up to date and then one of them will become
a leader.

**Comment by varunudacity** [comment]
Even easier perhaps:


https://curl.haxx.se/docs/manpage.html#--post301

The --post301 should send the original post data to the redirected URL.
That said, returning 307 instead of 301 would probably work automatically
on more clients.

**Comment by otoolep** [comment]
@varunudacity -- please review the cluster management documentation, as I believe it will answer your question:

https://github.com/rqlite/rqlite/blob/master/doc/CLUSTER_MGMT.md

**Comment by otoolep** [comment]
So add your 3 bigger nodes, and once those are added, remove the smaller nodes one-by-one.

**Comment by otoolep** [comment]
As for the original issue, the Disco Service API is a bit awkward to use by `curl`. I think it deserves a dedicated binary, for interacting with it. It would be quite easy to do.

**Comment by otoolep** [comment]
@varunudacity -- I think you are right, and that the Discovery Service should return 307 or 308. If it did then `curl` would just work. However I am reluctant to do that just yet, as it would break older versions of rqlite. I'll may make it in the future though.

In the meantime I have updated the docs to deal with this. It turns out `curl` supports an option to tell it not to change the method, and to resend the body. With this in place the docs are now useful again.

See change: https://github.com/rqlite/rqlite/commit/506f6b73b7041d7e8d1bab2b59f800543def94a2

Thanks again for catching this.
