### ISSUE TITLE
SQL.js and offline support  

### ISSUE THREAD

**Issue by sebastianmacias** [rqlite/rqlite#394]
Hi there, 

What would be involved in order to be able to use [sql.js](https://github.com/kripken/sql.js/) as a SQLite node running on a Web Browser and syncing to rqlite server side.

Thanks for any tips

**Comment by otoolep** [comment]
Thanks for the question.

This is not possible without a (possibly very) large amount of work, since rqlite is built using Go and C. You'd also need the Raft layer available in Javascript too. It may not even be practical, since browser environments come and go, and distributed consensus doesn't really work in that sense.
