### ISSUE TITLE
Are you planning to release a Maven project for this?

### ISSUE THREAD

**Issue by ppsanyal1** [rqlite/rqlite#433]
This will help imports easier for Java projects

**Comment by otoolep** [comment]
If you mean rqlite itself, I don't really follow what you want. A Maven project to pull down a release of the database and spin it up? In either case, I have little experience with Maven and would need someone else to work on this.

FWIW, the unit testing I put together for the Java client pulls down a Docker container running rqlite.

**Comment by ppsanyal1** [comment]
Yeah I actually mean rqlite itself. I saw your Java client and I am not talking about that. My concern is if I decide to use rqlite, I don't want to download it from your github, compile it and upgrade my production environment with the latest. I would rather prefer a centralized repository where you publish the latest release, and our build too (maven in this case) should be able to automatically download it. 

If that doesn't work, at least having a centralized repository for downloading the compiled executables/components should be of great help.

**Comment by otoolep** [comment]
OK, thanks for the clarification. You have two options instead of Maven.
- Download and run the published docker container.
- Download the prebuilt binary for your OS from GitHub (see https://github.com/rqlite/rqlite/releases). You don't need to compile anything.
Unfortunately I don't see myself doing any Maven work -- it's not something I'm that familiar with, and want to concentrate on the core database and client libraries. Help is always welcome however.

**Comment by otoolep** [comment]
I believe I've answered this question. It might be more fruitful for any further discussion to take place on the rqlite Google Group.

**Comment by ppsanyal1** [comment]
thanks
