### ISSUE TITLE
Rqlite unable to start http address when leader is not reachable

### ISSUE THREAD

**Issue by RameshRM** [rqlite/rqlite#529]
@otoolep The server doesnt start for some reason when the `join` address is not reachable. The DB & peers list get mixed up and even starting in standalone mode dont work, What is the best way to handle this? The only way i can recover is after deletion of the DB Folder, which doesn't sound right for me

**Comment by otoolep** [comment]
Can you provide a little more detail? Have you messed up the configuration of your cluster? Can you provide step-by-step instructions on how to reproduce this issue?

**Comment by RameshRM** [comment]
Sure, 


1. Started Leader node on `standalone` mode
`rqlited -http-addr 0.0.0.0:4001 -raft-addr x.x.x.x:4002 -http-adv-addr x.x.x.x /etc/opt/db_folder`
> `rqlite` started and `http` interface is up and running @ port *4001*

2. Started follower with join address
`rqlited -http-addr 0.0.0.0:4001 -raft-addr x1.x1.x1.x1:4002 -http-adv-addr x1.x1.x1.x2 -join http://x.x.x.x:4001 /etc/opt/db_folder`

>Logs : 

```
[rqlited] 2018/08/18 23:00:35 rqlited starting, version v4.3.0, commit 2883094c2b32cee035f44c1dce55326aaf36af9f, branch master
[rqlited] 2018/08/18 23:00:35 go1.9.1, target architecture is amd64, operating system target is linux
[store] 2018/08/18 23:00:35 ensuring /etc/opt/db_folder exists
[store] 2018/08/18 23:00:35 SQLite in-memory database opened
[mux] 2018/08/18 23:00:35 mux serving on `x1.x1.x1.x1:4002`, `x1.x1.x1.x1:4002`
[store] 2018/08/18 23:00:35 waiting for up to 2m0s for application of initial logs
2018/08/18 23:00:35 [INFO] raft: Node at `x.x.x.x:4002` [Follower] entering Follower state (Leader: "")
2018/08/18 23:00:36 [WARN] raft: EnableSingleNode disabled, and no known peers. Aborting election.
[rqlited] 2018/08/18 23:02:35 failed to open store: timeout waiting for initial logs application
```

At this time `rqlite` dont start, because `leader` is not reachable and timesout

2.1 Now starting the follower in standalone mode: 
`rqlited -http-addr 0.0.0.0:4001 -raft-addr x1.x1.x1.x1:4002 -http-adv-addr x1.x1.x1.x1 /etc/opt/db_folder`

> At this time sometimes even standalone dont start

**Comment by otoolep** [comment]
There may be some sequencing issues that might be improved within the code, but fundamentally the reason is this:

-- the node has joined a cluster, and now there are two nodes in the cluster.
-- when the leader is taken down, the cluster cannot elect a new leader, since it can't reach quorum (2 nodes are required to elect a new leader).
-- the node won't even start up properly, since it needs to contact a leader.

A cluster with two nodes doesn't make sense. It's too vulnerable to failures like this. Instead run 3 nodes, that way a new leader can be elected almost immediately if the first leader fails. 

You can read https://github.com/rqlite/rqlite/blob/master/DOC/CLUSTER_MGMT.md for more details. 

I am not planning any code changes to address this particular failure, since running 2-node clusters doesn't make much sense if you truly want fault-tolerance. Please re-open if I am missing something.
