### ISSUE TITLE
can we use rqlite as a libary?

### ISSUE THREAD

**Issue by the-oaks** [rqlite/rqlite#571]
is it practically possible to use rqlite as a library that embedded in another Go application rather than a standalone cmd? If so, is it possible to provide a minimal working example (that replicate sqlite data)? or some hints on how shall we start on this minimal working example? thanks

**Comment by the-oaks** [comment]
thanks a lots

**Comment by narg95** [comment]
Hi, I know this issue is closed, but I am interested in this feature, I made some experiments in a fork and it is straightforward to get it embedded in a library. If you are open for this change I would be happy to open a PR with basically the following changes:

1. new package for the library e.g. `pkg/lib` 
2. A `Config` struct with all config settings e.g.:

```go
type Config struct {
	DataPath               string
	HTTPAddr               string
	HTTPAdv                string
	JoinSrcIP              string
	TLS1011                bool
	AuthFile               string
	X509CACert             string
	X509Cert               string
	X509Key                string
	NodeEncrypt            bool
	NodeX509CACert         string
	NodeX509Cert           string
	NodeX509Key            string
...
```
3. A new `Server` type which is able to `Start()` and `Stop()`
```go
type Server struct{
...
}

func (s *Server) Start(ctx context.Context, cfg *Config) error {
    // logic from main() using cfg instead of gloval vars
   // it starts the server async
}


func (s *Server) Stop() {
    // stops the server by signaling the stop
    // very likely canceling the context.Context
    // or reusing the `terminate` channel which is currently used with signal.Notify(terminate, os.Interrupt)
    // by sending an artificial os.Signal
}
```

5. [Optional] integrate the new `Config` and `Server` into the `cmd/rqlited/main.go` so there is only a centralized place for server bootstrapping 

What do you think?

**Comment by narg95** [comment]
This proposal is just a first step in having a library, because it will still communicate using http. The next step is to extract the handlers logic inside the `http/service.go` into a library. Exposing the `Store`, so that the client create the commands, might be sufficient or perhaps a wrapper around it would be needed due to some extra checks or more complex validations, in any case your expertise @otoolep  will be required here =)

**Comment by otoolep** [comment]
I'm not against this in principle, and am open to your changes. However I do have one practical concern -- I don't want to be limited in the future making changes to the structure of the rqlite implementation because folks have started relying on an API other than the HTTP API. This may not be an issue in practise (particularly with versioning and forking) but that's my concern.

I also think there is too much logic at the `main` level and pushing some down into a server object is good idea -- so I'm always interested in such a change. But I won't promise to keep any API for `pkg/lib` the same going forward. Does that make sense?

**Comment by otoolep** [comment]
Thanks for the ideas.

No need for a disclaimer, nothing will state the package was written as importable package in the first place. Now if folks want to import it, that's up to do them of course.

So thinking about this a bit more -- and perhaps this is just a naming thing -- I don't want a `pkg/lib` directory. If you look at the structure of the code now, it's named after the system that code is most concerned with e.g. `http`, `store`. If you have identified a new concept -- _Server_ perhaps, then just create a `server` directory.

Just so you know, I can't guarantee I'll accept your patch. A clean designs with very extensive test coverage, has been a big goal of rqlite. So a new `server` component will need extensive test coverage, and a clean API, before I merge.

No one has proposed this large a refactor before to the code base, and until I see it, I'm can't be sure I'll merge. I just want to be clear up front, so you don't spend huge amounts of time only to be disappointed if I don't merge.

**Comment by narg95** [comment]
Thanks for the quick feedback!having the `server` package sounds good to me. The *disclaimer* was needed because the `pkg` is a convention for exportable/public code/library, but if we use `server` instead then it is not needed.

**Comment by narg95** [comment]
I think the most challenging part is to agree on the idea. To agree on implementation details I find it even simpler. And I think the idea so far is clear enough.
 
Although I do not want to minimize the change, but I do not expect a big refactor, I expect most changes to be just grouping of existing functionality into library code, so nothing new. 

The system test of rqlite will help to validate that the existing functionality remains intact. For new functionality I will for sure add tests.

In the first PR I expect to move the code from `main.go/main()` to `server.go/Start()` and global vars will be wrapped into a `Config` struct. The change should be straightforward to review. Here system tests will proof that the refactor still produces a functional rqlited binary. I already wrote an integration tests in my local branch for experimenting, it creates a cluster as explained in [README.md](https://github.com/rqlite/rqlite#forming-a-cluster) with three servers instantiated with the library listening on different ports. Let me know if you will be interested in this kind of integration tests written in go code, they differ from normal unit tests in that they open ports and create folders and files, if a distinction is needed we could skip them using the conditional test execution flag `-short`.

For the second PR, I expect something similar. Although I am not sure if we really will need an extra abstraction on top of the `Store` or if the `Store` is good enough to be exposed as library, in the later case the change will be much smaller.

So I will start with the PR if that sounds good to you!

Cheers!

**Comment by otoolep** [comment]
Sure, move ahead and I'll take a look.

**Comment by leaanthony** [comment]
I can see rqlite doing really well as a distributed, in-memory caching solution. It would be so great if that was achievable without having to deploy standalone servers, but rather incorporate it into existing services as a library.

**Comment by kcmvp** [comment]
Any plan to implement this feature?

**Comment by otoolep** [comment]
I do not have any plans to do this.

**Comment by diptanu** [comment]
+1 for this. It would be great to have the ability to use this, especially for open source services where having this as a library would be easier for people to spin this up without needing to start the servers as a daemon.

**Comment by otoolep** [comment]
Yes, you can do that. It should work. But I won't support it, provide much guidance etc. :-) I also make zero promises about the interfaces of the packages in rqlite remaining stable. 

So you are very welcome to use the source (along with credit and copying over the license), I just want you to know what kind of support to expect.

**Comment by floren** [comment]
Very good, thank you!
