### ISSUE TITLE
What if follower apply fails

### ISSUE THREAD

**Issue by chuntaojun** [rqlite/rqlite#634]
If the SQL executed is an insert or update statement, and if the execution fails on the follower side (non-sql logic error and constraint violation), I would like to see whether there is any problem if the error is put in the response in the code

```golang
case execute, query:
		var d databaseSub
		if err := json.Unmarshal(c.Sub, &d); err != nil {
			return &fsmGenericResponse{error: err}
		}
		if c.Typ == execute {
			r, err := s.db.Execute(d.Queries, d.Tx, d.Timings)
			return &fsmExecuteResponse{results: r, error: err}
		}
		r, err := s.db.Query(d.Queries, d.Tx, d.Timings)
		return &fsmQueryResponse{rows: r, error: err}
```

**Comment by otoolep** [comment]
I might not quite be following you. Are you saying what will happen if a follower fails to apply a change to the database, which has been committed to the log and applied with error on the leader? That is a serious failure in the system, and the node should be removed from the cluster.

Is that your question? There really is no point sending errors back to the leader, because it's a situation the leader can't do anything about.

**Comment by chuntaojun** [comment]
> I might not quite be following you. Are you saying what will happen if a follower fails to apply a change to the database, which has been committed to the log and applied with error on the leader? That is a serious failure in the system, and the node should be removed from the cluster.
> 
> Is that your question? There really is no point sending errors back to the leader, because it's a situation the leader can't do anything about.

My problem is, suppose there are three nodes A, B, and C, the leader is A, and B and C are followers. If there is a data modification sql statement, apply is executed correctly on A and B nodes, and it is impossible for C for other reasons. Execution (regardless of the crash of sqlite), I see in your code that the error during SQL execution is not said to be thrown to the state machine. I think in the case of some non-logical errors, should I throw an error and then trigger the stop of the state machine?

**Comment by otoolep** [comment]
By the time the follower attempts to apply the log entry the SQL database, the state machine _has already moved forward_. The authoritative record of what state the system is in is the Raft log, not the SQLite database.

The failing node should certainly be removed from the cluster, but "stopping the state machine" would mean the entire system fail if a single node failed, which is what rqlite is built to avoid.

**Comment by otoolep** [comment]
Can you explain what is the situation you're trying to deal with? That a node may fail to apply a change to the database is possible. But why would you want to shut down the whole system because a single node fails?

**Comment by chuntaojun** [comment]
Because we are going to make a distributed relational database based on raft, and build a distributed configuration center on this basis. If the follower apply fails, data query inconsistencies may occur.

**Comment by otoolep** [comment]
That is an argument for better alerting and monitoring on every node, so you know when it fails. I could certainly do that, right now you just have to monitor the logs on each node, and check that the "commited" log number does not lag behind other nodes (which is in node status).

But signalling an "apply" error back to the leader doesn't get you anything. The leader can do nothing with that information since the Raft log has already been changed. You are better to just monitor each node directly yourself, and then apply your own policies. If you want to shutdown the cluster, that's fine.

**Comment by chuntaojun** [comment]
Thank you for your patient solution. My team and I are discussing it. Thank you

**Comment by chuntaojun** [comment]
Your idea is to say, let me monitor log apply and do the corresponding node removal logic

**Comment by otoolep** [comment]
Yes.

You should learn about the [status and diagnostics API](https://github.com/rqlite/rqlite/blob/master/DOC/DIAGNOSTICS.md). There should be enough information in there to detect an unhealthy node -- primarily if you compare the leader commit index to a follower commit index.

I do have some ideas to add more information to that output, which would make monitoring easier.

**Comment by otoolep** [comment]
Nothing more to do here, specifically for this issue.
