### ISSUE TITLE
a lot of requests to rqlite 

### ISSUE THREAD

**Issue by Dorsosiv** [rqlite/rqlite#844]
Hi, the rqlites get a lot of requests (not just GET , also UPDATE and PUT) which as a result increases the log entries in the raft.

my question is should I increase the amount of log entires for the flag --raft-snap to make it create less snapshots which will take less memory from the in-memory disk. 
how will this change will affect the recovery of a node from crashing in case one of the 5/3 instances dies ? 
Note, we already increased the amount from the default 8192 to 12288.

**Comment by otoolep** [comment]
Is there an actual problem you're trying to solve? Something you would like to change? If you increase `--raft-snap` the following will happen:

- snapshots will happen less often (assuming your rate of INSERTs doesn't change.
- the snapshot processing will take longer when it does happen, because it may have more log data to process.
- it won't affect the size of the SQLite database in memory. That depends on the amount of data you send to rqlite.

Does that help?

**Comment by Dorsosiv** [comment]
ok I think Ill keep the snapshot value as we have set it before, A bit above the default.

There was a small problem , we tried to understand what could cause the rqlites in memory to get OOMkilled after 3 hours of work.

I thought that the snapshot will have an affect. however it appears that they do not have. And it would be better to test with the dbstat table the resources the tables we have in rqlite are taking. 

I wonder about the .expvar command. what are the data that you show there. because I tried to see if there would be something useful but we did not find anything related to consumption. But we did find the snapshot rqlite has taken.
