### ISSUE TITLE
Better management of dependencies

### ISSUE THREAD

**Issue by otoolep** [rqlite/rqlite#87]
rqlite doesn't explicitly manage dependencies, and when a release is made, pulls in the dependencies in whatever state they are at. This is not ideal, and makes it difficult to reproduce a build.

**Comment by otoolep** [comment]
With a move to Go 1.6, "vendoring" would probably be best.

**Comment by joonas-fi** [comment]
Current best practice is to use Dep [1]. It's really easy to use - I wish I started using it earlier because it was not as scary as I thought it would be. It's basically just `$ dep init` once to start using it and `$ dep ensure` at the beginning of your build process.

When Go modules mature (currently in beta), switch to using it.

[1] https://github.com/golang/go/wiki/vgo#current-state

> For any production workloads, use dep, or migrate to it if you have not done so already.

**Comment by otoolep** [comment]
Yes, I'm considering doing this for v5.0.

**Comment by otoolep** [comment]
Done via 'go mod'.

See https://github.com/rqlite/rqlite/pull/563
